[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[etherscan]
sepolia = { key = "NBHMA2RMXVZBZBWVMUNJD6PU646965411Y" }
[rpc_endpoints]
sepolia = "https://rpc.sepolia.org"
sepolia_backup = "https://api.zan.top/eth-sepolia"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
